### ISSUE TITLE
App running on everyone's machine

### ISSUE THREAD

**Issue by MrJadaml** [andotherthings/cadence#1]
As the lead, I want to make sure that everyone who is working on this app has it up and running on their machine, so that I know that everyone is set up to make contributions

Forked & Cloned
- [x] Sam
- [x] Metta
- [x] Krsto
- [x] Ross

**Comment by mtcrouse** [comment]
Forked and cloned, everything working fine

**Comment by kculafic** [comment]
Also forked, and clowned. Working.
