### ISSUE TITLE
Setup routes for Cards

### ISSUE THREAD

**Issue by MrJadaml** [andotherthings/cadence#10]
As a user, I want to be able to have lots of flash cards with different questions, so that I can learn all the things!

**Comment by MrJadaml** [comment]
@smk291 this one will be pending @mtcrouse finishing #11. You can start by stubbing out that knex query in the mean time.

**Comment by smk291** [comment]
OK, I'll create the following routes: 

cards: get, post, patch, delete
decks: get, post, patch, delete
cards_decks: get, patch(?)

**Comment by smk291** [comment]
May I add humps and boom to the package.json?

**Comment by MrJadaml** [comment]
Humps 👍 
Boom 👎
