### ISSUE TITLE
Setup DB Tables

### ISSUE THREAD

**Issue by MrJadaml** [andotherthings/cadence#11]
As a dev, I need to be able to store data about Cards and Decks, so that I can save it.

**Cards**
_has_many Card_Decks_
:question
:answer

**Deck**
_has_many Card_Decks_
:topic

**Card_Deck**
_belongs_to Deck_
**belongs_to Card**

**Comment by MrJadaml** [comment]
let's use [Knex](http://knexjs.org/) for this.

**Comment by MrJadaml** [comment]
@mtcrouse What do you think about adding an additional attribute to the Card table for a resource url that would link to docs or a blog that dives further into the explanation of a Card?
via: https://github.com/andotherthings/cadence/issues/6#issuecomment-277318923

**Comment by mtcrouse** [comment]
I think that's a good idea -- I'll add a resource_url column that defaults to null.

**Comment by MrJadaml** [comment]
Completed with #12
