### ISSUE TITLE
User Profile Wireframe

### ISSUE THREAD

**Issue by MrJadaml** [andotherthings/cadence#2]
As a user, I want to be able to have a profile page with my information, so that I can personalize the my UX

- [x] Create wireframe
- [x] Peer review wireframe
- [x] Accepted final wireframe

**Comment by kculafic** [comment]
![profile view wireframe](https://cloud.githubusercontent.com/assets/20747225/22754427/5a082e36-edf4-11e6-89b5-302c30c20d07.jpg)

**Comment by mtcrouse** [comment]
I like this as a basic user page! This might be for the future, but it would be nice to be able to sort the decks by how proficient the user is at that topic (based on the % correct, how recently the deck has been reviewed, etc.), especially if the user has a ton of decks.

**Comment by kculafic** [comment]
I dig this idea. It'd be really cool to have a visual chart to illustrate proficiency.

**Comment by MrJadaml** [comment]
I am marking this wireframe as accepted and created an issue to build this out with #24
