### ISSUE TITLE
Update Sam's Github Photo

### ISSUE THREAD

**Issue by MrJadaml** [andotherthings/cadence#5]
As a project manager, I would like for ALL my laborers to have identical Github photos, so that I can be amused.

- [ ] Get Sam a blue collard shirt 👕
- [ ] Grow Sam a solid beard and mustache 👨🏻
- [ ] Retake Sam's photo
- [ ] Update Sam's :octocat: photo

**Comment by mtcrouse** [comment]
I would like to see a collard shirt, although it sounds like it would be green. 
- [x] SPELLING BURN 🔥
