### ISSUE TITLE
Create Seed Data

### ISSUE THREAD

**Issue by MrJadaml** [andotherthings/cadence#6]
As a dev, I would like to have some dummy data to use when building out the app, so that I can see what the cards will look like with data.

Work from the draft schema data we came up with to help shape what this seed data will look like. Probably something like 6 or so cards with Questions and Answers.

**Comment by MrJadaml** [comment]
If everyone can come up with two questions w/ answers that would be helpful. Try to keep both the question and answer somewhat concise as it needs to fit on a flashcard. Think interview questions like "what is polymorphism" or "what is scope".

When you have come up with your two Q&As post them here.

@smk291 @rsstdd @mtcrouse @kculafic

**Comment by rsstdd** [comment]
This could be too verbose... Regardless, here are my suggestions.

Q:  What is a closure, and how/why would you use one?
A: Combination of a function bundled together (enclosed) with references to its surrounding state (the lexical environment).
        * callbacks; params to higher-order functions (map, reduce, filter) 
Q: What is a Promise and why would you use one?
A:  Avoid callbacks (callback hell); concise way to work with async js code
    * fulfilled, pending, and rejected

**Comment by MrJadaml** [comment]
@rsstdd If you find yourself using "and" I would just make two questions out of it. For the first one I would keep it as simple as "_What is a closure?_" then maybe another card for "_Why would you use a closure?_". For the answer to the first one I would avoid having to use parens/subtext. So: "_A closure is a function that retains access to its lexical scope_". From there then you could even create a questions like "_What is lexical scope?_"

What are the asterisks for?

**Comment by MrJadaml** [comment]
Group, keep in mind that we only have so much card real estate for the answers. If we keep our questions simple our answers can also be kept more concise. We also have the option to provide _extended answers_ in the form of a link to a resource diving further into the topic. 

We could even hyperlink to other cards from within a card. Using the example above, target keywords/topics like "lexical scope" and have them link to corresponding cards.

**Comment by rsstdd** [comment]
@MrJadaml, those asterisks are leftover formatting from Evernote. I should have cleaned those up.

I thought those might be too long. Let's break them up:

**Q:** What is a Promise?
**A:** An object used for asynchronous computations.

**Q:** What are the states of a Promise?
**A:** Pending, Fulfilled, Rejected

**Q:** What does _this_ refer to in JS functions?
**A:**  _this_  refers to the object that a function is a method of.

**Q:** Why would you use a Promise?
**A:** To avoid callbacks

**Q:** What is a Closure?
**A:** A function enclosed with references to its outer state.

**Comment by smk291** [comment]
I'll convert all of this to the draft schema and suggest a few entries of my own. Thanks for the material, and sorry for not getting to his sooner.

**Comment by MrJadaml** [comment]
Further clarification on some of those answers.

Q: What is a Promise?
*A: A promise represents the value of an asynchronous operation that is not necessarily know at the time of execution.

Q: What are the states of a Promise?
A: Pending, Fulfilled, Rejected

Q: What does `this` refer to in JS functions?
*A: `this` refers to the object that is invoking the function.
* This is going to be a tough flashcard question since the value of this is so contextual. You could create a series of questions for `this` providing a concise context to also get concise answers but for now these first sample QAs I would keep them more straight forward.

Q: Why would you use a Promise?
*A: Promises offer an alternative to performing asynchronous operations that are easier to reason about relative to callbacks.

Q: What is a Closure?
*A: A closure is a function that retains access to its lexical scope.

**Comment by mtcrouse** [comment]
Q: What is the Big O of binary search?
A: O(log n)

Q: What is the Big O of bubble sort?
A: O(n^2)

I know Galvanize doesn't focus on these sorts of things very much but they make for good flashcard questions.

**Comment by MrJadaml** [comment]
Completed in #16
